# Generated by Django 5.0.4 on 2024-04-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingr_supp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingr',
            name='ingr_exp',
            field=models.DateField(),
        ),
    ]
