# Generated by Django 5.0.4 on 2024-04-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingr_supp', '0002_alter_ingr_ingr_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supp_name', models.CharField(max_length=50)),
                ('Supp_quant', models.IntegerField(default=0)),
                ('Supp_desc', models.CharField(max_length=50)),
                ('Supp_catg', models.CharField(max_length=50)),
                ('Supp_cost', models.FloatField(default=0.0)),
                ('Supp_suppNo', models.CharField(max_length=50)),
                ('Supp_exp', models.DateField()),
                ('Supp_batch', models.CharField(default='00001', max_length=5)),
                ('Supp_date', models.DateField()),
                ('Supp_act', models.BooleanField(default=True)),
            ],
        ),
    ]
