# Generated by Django 5.0.3 on 2024-04-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordermodule', '0002_cart_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
