# Generated by Django 5.0.3 on 2024-04-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermodule', '0005_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
